# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: "default"

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CmdLine@2
  inputs:
    script: |
      cd ./Users/katalon/Downloads/Katalon_Studio_Engine_MacOS-8.6.0/Katalon Studio Engine.app/Contents/MacOS
      pwd
      katalonc -noSplash -runMode=console -projectPath="C:\Users\phonghnguyen\Katalon Studio\studio-3017-main\test.prj" -retry=0 -testSuitePath="Test Suites/healthcare-tests - TS_RegressionTest" -browserType="Chrome" -executionProfile="default" --config -webui.autoUpdateDrivers=true
