# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: katalon-mac-mini

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CmdLine@2
  inputs:
    script: |
      cd ./Users/katalon/Downloads/Katalon_Studio_Engine_MacOS-8.6.0/Katalon Studio Engine.app/Contents/MacOS
      pwd
- task: katalonTask@1
  inputs:
    version: '8.5.5'
    executeArgs: '-testSuitePath="Test Suites/healthcare-tests - TS_RegressionTest" -browserType="Chrome" -executionProfile="default" -apiKey="f70e7a9f-9042-4e64-8b77-2329a3ba4cba" --config -webui.autoUpdateDrivers=true'